#!/usr/bin/env bash
#
# Use on Ubuntu 16.04 LTS
#
# Installs docsDoc to Raneto in users home folder. Do not run as root.
#
# Run from the docsDoc directory

curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -

sudo apt-get install -y nodejs

git clone https://github.com/gilbitron/Raneto.git ~/raneto

cp -a ~/raneto/example ~/raneto/docsdoc

sed --in-place 's/example/docsdoc/g'\
  ~/raneto/package.json

sed --in-place 's/Raneto[[:space:]]Docs/docsdoc/'\
  ~/raneto/docsdoc/config.default.js

RAND="$(openssl rand -base64 $(($(($RANDOM%17))+23)))"

sed --in-place "s@admin@${RAND}@g"\
  ~/raneto/docsdoc/config.default.js

cd ~/raneto/docsdoc

rm -rf content/*

git init

git remote add docsdoc https://github.com/dotdigital-digital/docsdoc.git

git fetch docsdoc

git checkout docsdoc/master -- content

git checkout docsdoc/master -- update

chmod +x update

mv update ../update

cd ~/raneto

npm install

npm start
